create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id uuid primary key,
  name text,
  full_name text,
  email text,
  username text,
  niche text not null default '',
  "toneOfVoice" text not null default 'CONSULTATIVE',
  "calendarLink" text not null default '',
  "onboardingCompleted" boolean not null default true,
  role text not null default 'REP',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  business_name text not null,
  city text not null default '',
  business_type text not null default '',
  phone text,
  email text,
  website_url text,
  website_status text,
  normalized_name text,
  normalized_phone text,
  normalized_domain text,
  dedupe_key text not null,
  status text not null default 'NEW',
  deployed_url text,
  site_status text not null default 'UNBUILT',
  vercel_deployment_id text,
  owner_id uuid,
  closed_deal_value numeric,
  closed_at timestamptz,
  stripe_checkout_link text,
  source_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists leads_dedupe_key_idx on public.leads (dedupe_key);
create index if not exists leads_owner_id_idx on public.leads (owner_id);
create index if not exists leads_updated_at_idx on public.leads (updated_at desc);

create table if not exists public.lead_notes (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null,
  contact_id text,
  content text not null,
  channel text,
  created_at timestamptz not null default now()
);

create index if not exists lead_notes_lead_id_created_at_idx on public.lead_notes (lead_id, created_at desc);

create table if not exists public.call_analytics (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null,
  duration_seconds integer,
  overall_sentiment text,
  recording_url text,
  ai_summary text,
  agent_talk_time_pct numeric,
  customer_talk_time_pct numeric,
  interruptions integer,
  transcript_json jsonb,
  created_at timestamptz not null default now()
);

create index if not exists call_analytics_lead_id_created_at_idx on public.call_analytics (lead_id, created_at desc);

create table if not exists public.follow_ups (
  id bigint generated by default as identity primary key,
  lead_id uuid not null,
  lead_name text not null,
  rep_id text not null,
  title text not null,
  type text not null,
  due_date date not null,
  due_time text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create index if not exists follow_ups_lead_id_due_date_idx on public.follow_ups (lead_id, due_date, due_time);

create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  channel text not null default 'sales_floor',
  sender text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_channel_created_at_idx on public.chat_messages (channel, created_at);

create table if not exists public.demos (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid,
  lead_name text not null,
  selected_date date not null,
  selected_time text not null,
  meet_link text not null,
  rep_id uuid not null,
  rep_email text,
  created_at timestamptz not null default now()
);

create index if not exists demos_rep_id_idx on public.demos (rep_id);
create index if not exists demos_selected_date_idx on public.demos (selected_date);
create index if not exists demos_lead_id_idx on public.demos (lead_id);

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

drop trigger if exists set_leads_updated_at on public.leads;
create trigger set_leads_updated_at
before update on public.leads
for each row
execute function public.set_updated_at();

create or replace function public.handle_auth_user_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (
    id,
    email,
    name,
    full_name,
    username
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(coalesce(new.email, ''), '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', split_part(coalesce(new.email, ''), '@', 1)),
    split_part(coalesce(new.email, ''), '@', 1)
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_auth_user_created();

alter table public.users disable row level security;
alter table public.leads disable row level security;
alter table public.lead_notes disable row level security;
alter table public.call_analytics disable row level security;
alter table public.follow_ups disable row level security;
alter table public.chat_messages disable row level security;
alter table public.demos disable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant all on all tables in schema public to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;
